// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqHgRuda3DElbBXo9AXgENG6BiCDOFFGs',
    appId: '1:1013327800337:web:13176148295c25840fa9b0',
    messagingSenderId: '1013327800337',
    projectId: 'harmonia-31e51',
    authDomain: 'harmonia-31e51.firebaseapp.com',
    storageBucket: 'harmonia-31e51.appspot.com',
    measurementId: 'G-ECXG3WW0VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAofjYKNVUU19GVe2ED0-OW9qvDZhnS_2U',
    appId: '1:1013327800337:android:bd8d8d8d4e34d9eb0fa9b0',
    messagingSenderId: '1013327800337',
    projectId: 'harmonia-31e51',
    storageBucket: 'harmonia-31e51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCo8VmxPalBK9wCY9B0ho_6YCzqC5mS28',
    appId: '1:1013327800337:ios:9a7a2f6c6922352b0fa9b0',
    messagingSenderId: '1013327800337',
    projectId: 'harmonia-31e51',
    storageBucket: 'harmonia-31e51.appspot.com',
    iosBundleId: 'com.example.harmonia',
  );
}
